# Generated by Django 4.2.3 on 2023-08-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Turno",
            fields=[
                ("id_turno", models.AutoField(primary_key=True, serialize=False)),
                ("turno", models.CharField(max_length=20)),
                ("hora_ini", models.TimeField()),
                ("hora_fin", models.TimeField()),
            ],
            options={
                "db_table": "turnos",
            },
        ),
    ]
