# Generated by Django 4.2.3 on 2023-08-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comedor_django", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="turno",
            name="cant_turno",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="turno",
            name="cant_turno_total",
            field=models.IntegerField(default=0),
        ),
    ]
