# Generated by Django 4.2.3 on 2023-08-05 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comedor_django", "0002_turno_cant_turno_turno_cant_turno_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("usuario", models.CharField(max_length=100)),
                ("clave", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("ape_p", models.CharField(max_length=100)),
                ("ape_m", models.CharField(max_length=100)),
                ("fec_nac", models.DateField()),
            ],
            options={
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_reserva", primary_key=True, serialize=False
                    ),
                ),
                ("id_usuario", models.IntegerField()),
                ("nombre", models.CharField(max_length=100)),
                ("ape_p", models.CharField(max_length=100)),
                ("hora_ini", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("accion", models.IntegerField()),
                (
                    "id_turno",
                    models.ForeignKey(
                        db_column="id_turno",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comedor_django.turno",
                    ),
                ),
            ],
            options={
                "db_table": "reserva",
            },
        ),
    ]
