# Generated by Django 4.2.3 on 2023-08-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comedor_django", "0003_usuario_reserva"),
    ]

    operations = [
        migrations.AddField(
            model_name="turno",
            name="estado",
            field=models.IntegerField(default=0),
        ),
    ]
