# Generated by Django 4.2.3 on 2023-08-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comedor_django", "0004_turno_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="correo",
            field=models.EmailField(default="n/a", max_length=100),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(default="n/a", max_length=20),
        ),
    ]
